repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    -   id: check-yaml
    -   id: check-json
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
    -   id: no-commit-to-branch
        args: ["--branch", "master"]
    -   id: check-added-large-files
        args: ['--maxkb=8192']
    -   id: check-merge-conflict
    -   id: detect-private-key
    -   id: pretty-format-json
        args: ['--autofix']
    -   id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]
-   repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
    -   id: black
        language: python
        types: [ python ]
        args: [ "--line-length=100" ]
-   repo: https://github.com/PyCQA/autoflake
    rev: v2.0.0
    hooks:
      - id: autoflake
        entry: bash -c 'autoflake "$@"; git add -u' --
        language: python
        args:
          [
            "--in-place",
            "--remove-all-unused-imports",
            "--remove-unused-variables",
            "--expand-star-imports",
            "--ignore-init-module-imports",
          ]
        files: \.py$
-  repo: https://github.com/pycqa/isort
   rev: 5.11.2
   hooks:
      - id: isort
        entry: bash -c 'isort "$@"; git add -u' --
        language: python
        args: ["--filter-files", "--profile", "black"]
        files: \.py$
