version: "3"
services:
  middleware:
    build:
      dockerfile: dockerfiles/DockerfileMiddleware
      context: .
    restart: always
    ports:
      - 8079:8079
    env_file: .env
    volumes:
      - ./data:/data
    depends_on:
      - serving
      - rabbitmq
  serving:
    image: pytorch/torchserve:0.6.0-cpu
    command: torchserve --start --ts-config /home/model-server/deployment_data/config.properties --models resnet-18=resnet-18.mar
    restart: always
    volumes:
      - ./src/serving/deployment_data:/home/model-server/deployment_data
  nginx:
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./data:/data:ro
    command: nginx -g 'daemon off';
    ports:
      - 8078:8078
    depends_on:
      - serving
      - middleware
  rabbitmq:
    image: rabbitmq
