"""First revision

Revision ID: 04b150a3b1ce
Revises:
Create Date: 2022-08-26 23:23:20.844592

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "04b150a3b1ce"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "classification_info",
        sa.Column("test_group_id", sa.String(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("image_name", sa.String(), nullable=False),
        sa.Column("target_class_id", sa.Integer(), nullable=False),
        sa.Column("predicted_class", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("test_group_id", "id"),
        schema="statistics_calculation",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("classification_info", schema="statistics_calculation")
    # ### end Alembic commands ###
